### ISSUE TITLE
Update to use SCS 3.2.3

### ISSUE THREAD

**Issue by bodono** [FlorianSchwendinger/scs#13]
I've just released v3.2.3 which comes with several improvements, see notes: https://github.com/cvxgrp/scs/releases/tag/3.2.3

**Comment by bnaras** [comment]
Thanks @bodono .  @FlorianSchwendinger I'll soon post a PR.

**Comment by bnaras** [comment]
@FlorianSchwendinger, and @bodono,  I've made a PR to review.

**Comment by FlorianSchwendinger** [comment]
The updated package is on its way to CRAN.

**Comment by bodono** [comment]
Awesome, thanks!
