### ISSUE TITLE
OpenMP

### ISSUE THREAD

**Issue by gmonaie** [FlorianSchwendinger/scs#6]
Can this library able to support scs with OpenMP enabled?

https://github.com/cvxgrp/scs/issues/51

**Comment by FlorianSchwendinger** [comment]
I looked at it at my system at it seems to use already multiple threads when viewing it in htop. Furthermore, I tried to restrict the environment variables as suggested in your link but saw no effect, but I might missed some thing. So I assume it is possible and I will look into it when I find the time, but I don't think this will be soon (not in 2021 maybe in in 2022).
