### ISSUE TITLE
Update to support SCS 3.0

### ISSUE THREAD

**Issue by bodono** [FlorianSchwendinger/scs#7]
Hi Florian,

The new version of SCS I'm about to release is overall much faster and more reliable, as well as supporting quadratics in the objective natively (and other new features).

The SCS 3.0 PR is here: cvxgrp/scs#169

If you have any spare cycles it also would be great to have your input on the website, in particular the R API, install instructions, and an example or two. The website would name you as the maintainer of the API of course.

Current API page here: https://www.cvxgrp.org/scs/api/index.html#interfaces

Here is the website source: https://github.com/cvxgrp/scs/tree/3.0.0/docs/src

**Comment by FlorianSchwendinger** [comment]
Hi Brendan,

Thank you for the info and sorry for the late reply.
This week I am still quite bussy but I will have a look at it next week.

**Comment by bnaras** [comment]
Hi @FlorianSchwendinger  and @bodono , I've already made all the changes to the R scs package for 3.0. I also added all the checks that Brendan had and they pass.  I'll commit and make a PR very soon.

**Comment by bodono** [comment]
I think the only way it could be using more cores without openMP is from linking in a multi-threaded blas / lapack. It uses blas / lapack to do the Anderson acceleration and to project onto the positive semidefinite cone.

**Comment by bnaras** [comment]
> @bnaras how do you want proceed? Should I wait for the [changes you suggested](https://github.com/FlorianSchwendinger/scs/pull/8#issuecomment-939064606)? We could also upload the new (current) version now and later make the name changes. What do you think?

@FlorianSchwendinger I will commit these changes later this week and make a PR.

**Comment by bnaras** [comment]
> Continuing [`pull/8#issuecomment-939350343`](https://github.com/FlorianSchwendinger/scs/pull/8#issuecomment-939350343) I tried the openMP support but saw in htop that it is currently using already all of my cores which solving bigger problems and setting the environment variables did not change that. So I will look later into this.

I tried looking into this myself too and I think that this requires linking to indirect version of the solver. We currently only link to the direct version for the R package. Could that make a difference @bodono ?

**Comment by bodono** [comment]
The direct version of the solver is the main version, the indirect version is really only required for huge problems. Other than the indirect solver, openMP is only used to parallelize some of the cone projections (eg, exponential cone). I think it's fine to not have it on by default if it's causing issues.

**Comment by FlorianSchwendinger** [comment]
> The direct version of the solver is the main version, the indirect version is really only required for huge problems. Other than the indirect solver, openMP is only used to parallelize some of the cone projections (eg, exponential cone). I think it's fine to not have it on by default if it's causing issues.

Ok, very interesting. I can have a look at adding the indirect solver, for the next release.
